### ISSUE TITLE
Event Specific Page

### ISSUE THREAD

**Issue by joshi008** [iiitkottayam/Dhruva#18]
**Is your feature request related to a problem? Please describe.**
No, its the initial website building part.

**Describe the solution you'd like**
Events specific page:
* Event title and poster. Then Register button design take it from already built design in accessories folder.
* Details and rules about the eventalong with date and time
* Then comes the organiser section and judges section.
![image](https://user-images.githubusercontent.com/54844760/131968676-2847d586-1635-458f-8ef9-193c2e77369f.png)

**Describe alternatives you've considered**
Discuss the design alternatives with designers and project maintainers.

**Additional context**
Prototype: https://www.figma.com/proto/4a8ZglxR98YOEQpmXu93Ng/Dhruva-team-library?page-id=0%3A1&node-id=948%3A51&viewport=241%2C48%2C0.2&scaling=min-zoom

**Comment by faiz-hasan11** [comment]
Kindly give an update

**Comment by bindalsarthak03** [comment]
> Kindly give an update

Event name section is done.
Event details section is done.
