### ISSUE TITLE
White spaced border after closing Hamburger in Navbar (Mobile view)

### ISSUE THREAD

**Issue by joshi008** [iiitkottayam/Dhruva#25]
**Describe the bug**
There is a white space once we open and close the hamburger in the mobile view. This white space would go awat once we scroll down.

**To Reproduce**
1. Go to 'our preview build website at https://dhruva-nextjs-mu6loruwl-dhruva-team.vercel.app/ ' in mobile view
2. Click on 'hamburger'
3. See the white space in the right side of the page.

**Expected behavior**
There should not be a white border in the right side.

**Screenshots**
![WhatsApp Image 2021-09-05 at 4 28 46 PM](https://user-images.githubusercontent.com/54844760/132124376-6c95c73b-3262-4108-835a-2dcd6304306e.jpeg)

**Desktop (please complete the following information):**
 - OS: Android
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: Any device

**Comment by Himanxu1** [comment]
Assign this to me. @joshi008

**Comment by joshi008** [comment]
@Himanxu1 , we would like you to contribute towards the website and improve it. But the website is being build for the Technical Fest of IIIT Kottayam and therefore does not allow contributions outside institute till now. 
Would open it for others as well soon.

**Comment by GetPsyched6** [comment]
I'm ready to take this issue up

**Comment by ishaan5199** [comment]
i'll collab with him
