### ISSUE TITLE
Landing Page - Section 1 - First visual element

### ISSUE THREAD

**Issue by joshi008** [iiitkottayam/Dhruva#3]
**Is your feature request related to a problem? Please describe.**
No, its the initial website building part.

**Describe the solution you'd like**
Section-1 of the Landing Page: 
* A good title of the section by using your brainstorming or coordinating with trendles to come up with some catchy line to grab the first view attention of the website.
* Subtitle of the webpage, nice and catchy.
* Register and join discord button
* Socials icon for instagram, twitter, facebook, email

**Describe alternatives you've considered**
* We could make the background more expressive, and have good image as well. 

**Additional context**
Prototype: https://www.figma.com/proto/4a8ZglxR98YOEQpmXu93Ng/Dhruva-team-library?page-id=0%3A1&node-id=312%3A18&viewport=241%2C48%2C0.2&scaling=min-zoom

**Comment by GetPsyched6** [comment]
I'm ready to do this section

**Comment by starwiz-7** [comment]
@GetPsyched6  @nikhil9302 has already built the navbar component and stuff for this block. Would you please choose another block?
