### ISSUE TITLE
404 Not found Page Creation on wrong url

### ISSUE THREAD

**Issue by joshi008** [iiitkottayam/Dhruva#32]
**Is your feature request related to a problem? Please describe.**
No, its the initial website building part.

**Describe the solution you'd like**
404 not found page:
* Find out some good illustrations for our 404 page
* Make sure that the theme of the web page is maintained.
* 404 page should be rendered when the url does not exists in our directory, or we have no page to be rendered for it.

**Describe alternatives you've considered**
Discuss the design alternatives with designers and project maintainers.

**Additional context**
Design at https://www.figma.com/file/4a8ZglxR98YOEQpmXu93Ng/Dhruva-team-library?node-id=0%3A1

**Comment by RaiLokesh** [comment]
wanna work on this
