### ISSUE TITLE
Attendees & Speakers introduction section

### ISSUE THREAD

**Issue by joshi008** [iiitkottayam/Dhruva#37]
**Is your feature request related to a problem? Please describe.**
No, its the initial website building part.

**Describe the solution you'd like**
Attendees and speaker glimpse section:
* The section is half build in the figma file as displayed under.
![image](https://user-images.githubusercontent.com/54844760/132309274-66302cdf-edd9-464e-b402-0792b750a66a.png)

* The whole section inspiration is taken from https://www.experiencewelcome.com/
* This section would be the breif of whole technical fest and what all would be happening in it.
* Try to accumulate the animation with images as close as possible and make this section exact replica of https://www.experiencewelcome.com/ section.

**Describe alternatives you've considered**
Discuss the design alternatives with designers and project maintainers.

**Additional context**
Design at https://www.figma.com/file/4a8ZglxR98YOEQpmXu93Ng/Dhruva-team-library?node-id=0%3A1

**Comment by RaiLokesh** [comment]
can I work on this?
