### ISSUE TITLE
Menu close icon scrolling

### ISSUE THREAD

**Issue by starwiz-7** [iiitkottayam/Dhruva#42]
**Describe the bug**
While opening the menu in mobile screen view, we can scroll the background i.e landing page. The close icon also scrolls above thus it's not visible.

**To Reproduce**
1. Go to the Landing page
2. Click on hamburger menu
3. Scroll down.
4. One can see that close icon is not visible

**Expected behavior**
The close icon should be fixed and should not scroll down.

**Screenshots**
![iss1](https://user-images.githubusercontent.com/54806954/132672705-0d4a1ba9-b241-4e1b-bb35-7145bfa452d6.png)

**Smartphone (please complete the following information):**
 - OS: Android/iOS
 - Browser: Chrome, Firefox, Brave

**Additional context**
Suggestions:
1. Make the close icon fixed
2. Make a separate page for the menu and make the background opaque

**Comment by Alwinseb01** [comment]
@joshi008 i'd like to work on this
