### ISSUE TITLE
Landing Page - Section 3.5 - Speakers section

### ISSUE THREAD

**Issue by joshi008** [iiitkottayam/Dhruva#5]
**Is your feature request related to a problem? Please describe.**
No, its the initial website building part.

**Describe the solution you'd like**
Section-3.5:
* Design needs improvement as the image of one speaker is visible at a gance which would be bad for a first time viewer.
* Coordinate with designer for a new design
* Implement all the designs with the current color scheme and fot styling of the figma.

**Describe alternatives you've considered**
Discuss the design and its alternatives with your project maintainers and the designing team.

**Comment by jaswanthpallavolu** [comment]
I would like to do code for this section

**Comment by Anshu1882000** [comment]
I'm not doing this section anymore I've been assigned the sponsers page.
It's better if u contact Hrishabh or Aryan once.
