### ISSUE TITLE
Hamburger Open area not covering full screen and Content not alligned

### ISSUE THREAD

**Issue by joshi008** [iiitkottayam/Dhruva#64]
**Describe the bug**
Hamburger Open area not covering full screen

**Expected behavior**
The hamburger open tray should go full screen along with links in the middle of the screen and there should a slight darker background in the overlay of menu. Also the links are not correctly attached to some of the menu items.
All the menu items should be alligned in the center of the screen.
And the background should not be scrollable while menu is opened.

**Screenshots**
![image](https://user-images.githubusercontent.com/54844760/135489583-7df48ce0-c189-433f-b39b-697dc96ac1ac.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser : chrome

**Comment by ishaan5199** [comment]
I'll take up this issue

**Comment by GetPsyched6** [comment]
ready to collab with @ishaan5199
