### ISSUE TITLE
Event specific page needs updation

### ISSUE THREAD

**Issue by joshi008** [iiitkottayam/Dhruva#65]
### Feature to add
Add the tagline for each event as listed here: https://docs.google.com/document/d/1htWvIRy-7GJjD3G0ZmYWGtksWS4MYQ_kd_E-Sv2dNyQ/edit?usp=sharing for each event.
Remove organisers images and links instead add contact the organisers:
Name email and phone number.

**Comment by shashank1503-cipher** [comment]
I'll do it

**Comment by adityagi02** [comment]
me and @shashank1503-cipher  will collab on this, please do assign me also😃

**Comment by shashank1503-cipher** [comment]
I have made a PR regarding this, please review it once
