### ISSUE TITLE
Improve Sponsor section & add team details

### ISSUE THREAD

**Issue by joshi008** [iiitkottayam/Dhruva#66]
### Feature to add

Improve the sponsor section to have a clear view of the current sponsors we have according to the doc: https://docs.google.com/document/d/1n8mXbP-cx_Tzv6kAMqdqpzP9-g3F0LGf60u6Q1J3oXo/edit?usp=sharing

And add all the team details and gifs for the teams, adding appropriate sections for their roles.
https://docs.google.com/document/d/1fBAo1jprjbJ5Jv9f3hGMg0Rv7Rz3N0aumw-vO7t28Ks/edit?usp=sharing

**Comment by GetPsyched6** [comment]
I'm ready to take this issue up
