### ISSUE TITLE
Landing Page - Section 5 - Prizes and Sponsors 

### ISSUE THREAD

**Issue by joshi008** [iiitkottayam/Dhruva#7]
**Is your feature request related to a problem? Please describe.**
No, its the initial website building part.

**Describe the solution you'd like**
Section-5 of the Landing Page:
* Choose a gradient style of the background.
* Make grid or anything you like for the prizes and sponsors in the prototype. 
* Make sure the website is responsive and the grids fall back to one over another in mobile view.

**Describe alternatives you've considered**
Discuss the design alternatives with project maintainers and designers.

**Additional context**
Prototype: https://www.figma.com/proto/4a8ZglxR98YOEQpmXu93Ng/Dhruva-team-library?page-id=0%3A1&node-id=312%3A18&viewport=241%2C48%2C0.2&scaling=min-zoom

**Comment by faiz-hasan11** [comment]
Kindly provide an update on work , the limit of 2 days has exceeded

**Comment by Anshu1882000** [comment]
Almost done. Will generate the PR by tomorrow

**Comment by faiz-hasan11** [comment]
Is is completed?
