### ISSUE TITLE
Landing Page - Section 6 - Want to be a sponsor & FAQ section

### ISSUE THREAD

**Issue by joshi008** [iiitkottayam/Dhruva#8]
**Is your feature request related to a problem? Please describe.**
No, its the initial website building part.

**Describe the solution you'd like**
Section-6 of the Landing Page:
* Button about us in section 2 issue is build. Try to take it from there if built, or make your own.
* Replicate the chat FAQ as close as possible.
* Make sure that the FAQs are responsive for mobile version as well.

**Describe alternatives you've considered**
Discuss the design alternatives with designers and project maintainers.

**Additional context**
Prototype: https://www.figma.com/proto/4a8ZglxR98YOEQpmXu93Ng/Dhruva-team-library?page-id=0%3A1&node-id=312%3A18&viewport=241%2C48%2C0.2&scaling=min-zoom

**Comment by ishaan5199** [comment]
I can take up this section.

**Comment by GetPsyched6** [comment]
Is it possible to Collab on this section?

**Comment by starwiz-7** [comment]
Yeah, if you guys want you can collab. I'll assign it to both of you

**Comment by ishaan5199** [comment]
> Yeah, if you guys want you can collab. I'll assign it to both of you

Yeah we'll collab
