### ISSUE TITLE
Landing Page - Section 7 - Footer

### ISSUE THREAD

**Issue by joshi008** [iiitkottayam/Dhruva#9]
**Is your feature request related to a problem? Please describe.**
No, its the initial website building part.

**Describe the solution you'd like**
Section-7 of the Landing Page:
* Replicate the footer design as in figma file. 
* Direct user to iiitkottayam social handels for the testing period.

**Describe alternatives you've considered**
Discuss the design alternatives with designers and project maintainers.

**Additional context**
Prototype: https://www.figma.com/proto/4a8ZglxR98YOEQpmXu93Ng/Dhruva-team-library?page-id=0%3A1&node-id=312%3A18&viewport=241%2C48%2C0.2&scaling=min-zoom

**Comment by shashank1503-cipher** [comment]
I could do this one

**Comment by starwiz-7** [comment]
@shashank1503-cipher Before starting to work on this block, just confirm the design once as we were thinking to tweak it a little.

**Comment by shashank1503-cipher** [comment]
Alright cool, I'll just check this one with prajjwal

**Comment by shashank1503-cipher** [comment]
I have made a pull request regarding this check once

**Comment by joshi008** [comment]
The issue has been resolved 90%,  waiting for some of the other PRs and then would merge it with some edit.
